# dropna()

In [1]:
import pandas as pd

In [5]:
df = pd.read_csv('train.csv')
print(df.shape)
df

(120, 15)

,train_number,train_name,source,destination,departure_time,arrival_time,distance_km,duration_hours,train_type,class,fare,available_seats,platform,running_days,rating
0,19270,Duronto Express,Howrah,Jaipur,18:01,14:32,1799.0,35.3,Express,CC,2956.0,353.0,11.0,Tue-Sun,3.6
1,12860,Rajdhani Express,Jaipur,Patna,22:49,21:36,1350.0,18.7,Superfast,CC,2640.0,11.0,NaN,Wed-Sun,3.6
2,17390,Duronto Express,Bhopal,Kolkata,12:20,01:01,1782.0,13.2,Superfast,2A,477.0,274.0,14.0,Daily,2.9
3,17191,Garib Rath Express,Howrah,Patna,01:56,09:55,1655.0,23.5,Passenger,1A,3460.0,NaN,4.0,Mon-Sat,4.5
4,17734,Duronto Express,Chennai Central,Bengaluru,13:10,12:08,2194.0,10.2,Superfast,SL,3450.0,43.0,13.0,Daily,4.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,14454,Intercity Express,Howrah,Chennai Central,00:36,14:45,237.0,11.8,Mail,1A,4353.0,140.0,11.0,Mon-Fri,3.3
116,20996,Tamil Nadu Express,Chennai Central,New Delhi,23:12,20:36,2331.0,21.8,Premium,SL,321.0,273.0,9.0,Mon-Fri,3.0
117,14731,Konkan Kanya Express,New Delhi,Pune,04:38,03:22,1453.0,7.2,Premium,2A,NaN,415.0,8.0,Mon-Fri,4.5
118,22965,Jan Shatabdi Express,New Delhi,Chennai Central,03:36,12:43,1975.0,18.4,Premium,CC,3699.0,95.0,3.0,Wed-Sun,4.1
119,20154,Duronto Express,Jaipur,Jaipur,14:26,20:52,168.0,20.1,Premium,1A,4347.0,226.0,11.0,Tue-Sun,3.7

### syntax -> df.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False, ignore_index=False)

### 1. Drop rows with any missing values (Default Behavior)

In [9]:
dropped_any = df.dropna()
# dropped_any = df.dropna(how='any', inplace=True)
print(dropped_any.shape)
dropped_any

(56, 15)

,train_number,train_name,source,destination,departure_time,arrival_time,distance_km,duration_hours,train_type,class,fare,available_seats,platform,running_days,rating
0,19270,Duronto Express,Howrah,Jaipur,18:01,14:32,1799.0,35.3,Express,CC,2956.0,353.0,11.0,Tue-Sun,3.6
2,17390,Duronto Express,Bhopal,Kolkata,12:20,01:01,1782.0,13.2,Superfast,2A,477.0,274.0,14.0,Daily,2.9
4,17734,Duronto Express,Chennai Central,Bengaluru,13:10,12:08,2194.0,10.2,Superfast,SL,3450.0,43.0,13.0,Daily,4.2
6,12466,Garib Rath Express,Chennai Central,Chennai Central,23:36,06:36,1649.0,6.4,Superfast,1A,3204.0,304.0,1.0,Tue-Sun,2.7
8,17578,Humsafar Express,Howrah,Ahmedabad,18:01,17:22,1496.0,7.2,Superfast,3A,1461.0,16.0,14.0,Daily,4.1
9,20322,Humsafar Express,Vijayawada,Bengaluru,10:33,02:56,570.0,6.7,Premium,CC,3341.0,329.0,5.0,Daily,3.2
10,13685,Konkan Kanya Express,Howrah,Pune,08:32,06:35,1135.0,23.8,Express,2S,2688.0,56.0,12.0,Wed-Sun,4.9
11,12769,Intercity Express,Ahmedabad,Kolkata,13:21,07:24,1453.0,8.2,Passenger,1A,4133.0,310.0,9.0,Mon-Sat,2.9
14,14433,Tamil Nadu Express,Vijayawada,Bengaluru,09:19,04:24,767.0,18.1,Express,1A,972.0,11.0,9.0,Tue-Sun,3.5
15,17311,Duronto Express,Mumbai Central,Chennai Central,08:07,07:34,472.0,24.7,Mail,2S,1093.0,317.0,10.0,Mon-Sat,4.1
16,17051,Humsafar Express,Pune,Jaipur,21:00,11:57,1131.0,7.9,Mail,CC,924.0,79.0,14.0,Wed-Sun,3.5
17,18420,Rajdhani Express,New Delhi,New Delhi,14:56,12:14,1245.0,8.5,Express,CC,2348.0,215.0,9.0,Mon-Fri,3.2
18,13184,Vande Bharat Express,Bhopal,Howrah,21:35,23:27,1471.0,3.4,Passenger,2A,3306.0,338.0,7.0,Mon-Fri,5.0
20,15385,Garib Rath Express,Ahmedabad,Bengaluru,11:43,23:10,639.0,11.5,Premium,SL,3845.0,478.0,5.0,Tue-Sun,4.7
24,14558,Vande Bharat Express,Patna,Mumbai Central,04:06,18:42,2046.0,17.7,Express,2S,4327.0,484.0,3.0,Wed-Sun,4.1
29,21998,Tamil Nadu Express,Lucknow,Chennai Central,11:36,19:34,1681.0,3.3,Express,1A,3340.0,24.0,2.0,Mon-Sat,3.0
30,12189,Shatabdi Express,Ahmedabad,Pune,21:48,19:27,489.0,29.2,Premium,2A,1705.0,465.0,4.0,Mon-Fri,4.7
33,16658,Garib Rath Express,New Delhi,Mumbai Central,17:50,01:48,808.0,31.7,Express,CC,3727.0,142.0,5.0,Mon-Sat,4.6
34,13899,Jan Shatabdi Express,Mumbai Central,Hyderabad,16:48,17:45,1938.0,33.3,Passenger,2A,3051.0,58.0,9.0,Wed-Sun,4.4
35,19734,Tamil Nadu Express,New Delhi,Vijayawada,01:33,20:09,2044.0,4.1,Premium,1A,1537.0,409.0,1.0,Wed-Sun,4.1
44,22555,Intercity Express,Chennai Central,Ahmedabad,05:40,03:54,323.0,14.5,Express,3A,2723.0,400.0,11.0,Mon-Sat,4.2
46,20433,Rajdhani Express,Chennai Central,Hyderabad,21:52,12:30,2324.0,27.4,Superfast,3A,4183.0,281.0,5.0,Daily,3.0
48,19513,Intercity Express,Pune,Kolkata,05:56,17:12,952.0,10.6,Superfast,3A,1454.0,85.0,5.0,Mon-Fri,2.7
49,14612,Konkan Kanya Express,Hyderabad,Lucknow,00:22,18:17,162.0,26.3,Mail,3A,3580.0,249.0,11.0,Tue-Sun,4.0
51,21555,Vande Bharat Express,New Delhi,Lucknow,18:43,08:11,788.0,19.4,Express,3A,2691.0,269.0,6.0,Tue-Sun,4.5
54,19099,Humsafar Express,Bhopal,Ahmedabad,20:46,20:53,2252.0,17.2,Express,1A,2226.0,6.0,14.0,Wed-Sun,2.5
56,22748,Deccan Queen,Pune,Kolkata,07:21,19:51,484.0,10.2,Superfast,2S,2807.0,370.0,11.0,Daily,3.5
58,20226,Intercity Express,Hyderabad,Lucknow,16:55,23:36,617.0,14.8,Mail,1A,954.0,327.0,13.0,Mon-Fri,4.0
59,15152,Garib Rath Express,Pune,Vijayawada,22:28,15:45,575.0,2.7,Mail,1A,224.0,497.0,2.0,Mon-Fri,3.2
60,22147,Rajdhani Express,Howrah,Ahmedabad,08:35,13:14,2100.0,13.0,Mail,CC,2325.0,314.0,9.0,Mon-Sat,4.2
61,13585,Duronto Express,Patna,Howrah,17:19,10:33,1768.0,9.2,Mail,3A,4074.0,214.0,7.0,Wed-Sun,4.7
65,13021,Konkan Kanya Express,Chennai Central,Pune,08:16,05:38,182.0,22.2,Express,2A,1772.0,477.0,8.0,Wed-Sun,2.8
69,21692,Vande Bharat Express,Patna,Chennai Central,11:29,08:30,150.0,5.0,Passenger,SL,795.0,401.0,5.0,Wed-Sun,3.7
73,16297,Vande Bharat Express,Chennai Central,Mumbai Central,21:31,19:15,548.0,16.7,Passenger,2S,3103.0,272.0,10.0,Daily,2.5
76,19629,Shatabdi Express,Howrah,Chennai Central,04:44,23:58,1923.0,14.3,Premium,CC,3119.0,151.0,9.0,Wed-Sun,2.7
77,21467,Duronto Express,New Delhi,Ahmedabad,06:36,07:24,2181.0,24.0,Superfast,1A,3178.0,482.0,10.0,Mon-Sat,3.4
80,18439,Rajdhani Express,Patna,Kolkata,21:16,02:46,2301.0,35.5,Mail,2S,4375.0,300.0,10.0,Daily,3.5
84,20529,Rajdhani Express,Pune,Hyderabad,12:06,19:09,2265.0,7.2,Premium,2S,3016.0,170.0,5.0,Wed-Sun,4.5
86,21268,Shatabdi Express,Chennai Central,Howrah,01:29,10:52,367.0,7.5,Premium,CC,4274.0,473.0,6.0,Tue-Sun,2.9
88,16859,Jan Shatabdi Express,New Delhi,Hyderabad,10:04,20:43,1177.0,11.7,Passenger,CC,4000.0,470.0,1.0,Tue-Sun,4.1
89,18331,Humsafar Express,Jaipur,Hyderabad,16:09,18:01,335.0,7.9,Passenger,CC,2208.0,363.0,9.0,Mon-Fri,4.3
91,20684,Rajdhani Express,Chennai Central,Jaipur,06:57,07:35,862.0,4.7,Premium,3A,336.0,14.0,4.0,Mon-Sat,4.8
92,19208,Rajdhani Express,Hyderabad,Bengaluru,01:54,13:48,1948.0,19.8,Passenger,2A,3004.0,375.0,10.0,Daily,2.6
94,14062,Shatabdi Express,Hyderabad,Pune,20:19,23:04,1352.0,35.4,Mail,2S,1483.0,3.0,13.0,Daily,4.3
95,12064,Garib Rath Express,Patna,Bengaluru,13:45,17:04,677.0,5.8,Mail,3A,4343.0,348.0,11.0,Mon-Fri,4.7
100,14695,Vande Bharat Express,Chennai Central,Vijayawada,21:40,20:14,1429.0,10.8,Mail,1A,1912.0,160.0,14.0,Mon-Fri,2.7
101,21687,Humsafar Express,Hyderabad,Howrah,17:00,23:12,2245.0,7.8,Mail,2A,4070.0,15.0,1.0,Wed-Sun,4.7
102,17258,Konkan Kanya Express,Pune,Hyderabad,12:40,23:52,1458.0,24.7,Passenger,2S,631.0,492.0,8.0,Tue-Sun,3.9
105,12391,Rajdhani Express,Mumbai Central,Patna,07:36,15:33,1431.0,21.4,Superfast,SL,2270.0,381.0,6.0,Mon-Sat,4.1
106,17892,Jan Shatabdi Express,Bengaluru,Chennai Central,15:19,19:00,348.0,11.5,Superfast,1A,2493.0,449.0,13.0,Tue-Sun,3.8
110,15099,Shatabdi Express,New Delhi,Kolkata,16:17,11:11,641.0,16.5,Passenger,2A,1789.0,33.0,9.0,Mon-Sat,3.1
114,19215,Rajdhani Express,Chennai Central,Patna,20:13,01:19,896.0,22.8,Premium,SL,1402.0,268.0,2.0,Mon-Fri,4.9
115,14454,Intercity Express,Howrah,Chennai Central,00:36,14:45,237.0,11.8,Mail,1A,4353.0,140.0,11.0,Mon-Fri,3.3
116,20996,Tamil Nadu Express,Chennai Central,New Delhi,23:12,20:36,2331.0,21.8,Premium,SL,321.0,273.0,9.0,Mon-Fri,3.0
118,22965,Jan Shatabdi Express,New Delhi,Chennai Central,03:36,12:43,1975.0,18.4,Premium,CC,3699.0,95.0,3.0,Wed-Sun,4.1
119,20154,Duronto Express,Jaipur,Jaipur,14:26,20:52,168.0,20.1,Premium,1A,4347.0,226.0,11.0,Tue-Sun,3.7

### 2. Drop rows only if all values are missing

In [10]:
dropped_all = df.dropna(how='all')
print(dropped_all.shape)
dropped_all

(120, 15)

,train_number,train_name,source,destination,departure_time,arrival_time,distance_km,duration_hours,train_type,class,fare,available_seats,platform,running_days,rating
0,19270,Duronto Express,Howrah,Jaipur,18:01,14:32,1799.0,35.3,Express,CC,2956.0,353.0,11.0,Tue-Sun,3.6
1,12860,Rajdhani Express,Jaipur,Patna,22:49,21:36,1350.0,18.7,Superfast,CC,2640.0,11.0,NaN,Wed-Sun,3.6
2,17390,Duronto Express,Bhopal,Kolkata,12:20,01:01,1782.0,13.2,Superfast,2A,477.0,274.0,14.0,Daily,2.9
3,17191,Garib Rath Express,Howrah,Patna,01:56,09:55,1655.0,23.5,Passenger,1A,3460.0,NaN,4.0,Mon-Sat,4.5
4,17734,Duronto Express,Chennai Central,Bengaluru,13:10,12:08,2194.0,10.2,Superfast,SL,3450.0,43.0,13.0,Daily,4.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,14454,Intercity Express,Howrah,Chennai Central,00:36,14:45,237.0,11.8,Mail,1A,4353.0,140.0,11.0,Mon-Fri,3.3
116,20996,Tamil Nadu Express,Chennai Central,New Delhi,23:12,20:36,2331.0,21.8,Premium,SL,321.0,273.0,9.0,Mon-Fri,3.0
117,14731,Konkan Kanya Express,New Delhi,Pune,04:38,03:22,1453.0,7.2,Premium,2A,NaN,415.0,8.0,Mon-Fri,4.5
118,22965,Jan Shatabdi Express,New Delhi,Chennai Central,03:36,12:43,1975.0,18.4,Premium,CC,3699.0,95.0,3.0,Wed-Sun,4.1
119,20154,Duronto Express,Jaipur,Jaipur,14:26,20:52,168.0,20.1,Premium,1A,4347.0,226.0,11.0,Tue-Sun,3.7