In [1]:
import pandas as pd

In [14]:
df = pd.read_csv('customer_spending_dataset.csv')
df.head(8)

     Name Gender     City Frequency      Item  Spends
0  Nitesh      M  Kolkata   Monthly     Pizza      62
1     Anu      M  Gurgaon     Never  Sandwich     113
2   Mukku      M  Kolkata     Daily     Pizza      64
3    Suri      M  Chennai    Weekly     Thali     144
4   Rajiv      F    Delhi      Once     Momos      76
5   Aarav      M    Patna      Once   Biryani      76
6   Priya      M    Delhi   Monthly  Sandwich      28
7   Rohan      F  Gurgaon   Monthly   Biryani      72

In [5]:
df.pivot_table(index='City', columns='Item', values='Spends', aggfunc='mean')

Item,Biryani,Burger,Dosa,Momos,Noodles,Paneer,Pasta,Pizza,Samosa,Sandwich,Thali,Vada
City,,,,,,,,,,,,
Bengaluru,NaN,122.0,44.0,135.0,NaN,NaN,91.75,19.0,69.333333,82.500000,80.0,NaN
Chennai,NaN,NaN,20.0,NaN,NaN,77.0,7.00,NaN,110.333333,NaN,114.0,125.0
Delhi,96.5,35.0,81.0,76.0,52.666667,NaN,131.00,NaN,102.000000,59.500000,23.0,NaN
Gurgaon,92.5,NaN,NaN,85.0,NaN,34.0,84.00,57.0,73.500000,107.500000,43.0,109.0
Hyderabad,NaN,NaN,72.0,74.0,NaN,NaN,142.00,70.0,NaN,68.000000,144.0,71.5
Jaipur,NaN,115.5,102.0,107.0,9.000000,108.0,NaN,61.0,65.000000,129.000000,103.0,NaN
Kolkata,73.0,NaN,NaN,116.0,133.000000,50.0,NaN,54.0,NaN,52.000000,NaN,45.0
Mumbai,NaN,NaN,NaN,84.0,144.000000,NaN,NaN,117.0,80.000000,113.000000,147.0,112.0
Patna,76.0,NaN,12.5,NaN,68.000000,98.0,114.00,103.0,140.000000,67.000000,NaN,NaN
Pune,81.0,NaN,20.0,141.0,59.000000,116.0,38.00,NaN,76.000000,79.666667,134.0,99.0

In [8]:
df.pivot_table(index=['City', 'Gender'], columns='Item', values='Spends', aggfunc='mean')

Item              Biryani  Burger   Dosa  Momos  Noodles  Paneer       Pasta  \
City      Gender
Bengaluru F           NaN   122.0    NaN  135.0      NaN     NaN  120.000000
          M           NaN     NaN   44.0    NaN      NaN     NaN   82.333333
Chennai   F           NaN     NaN   20.0    NaN      NaN     NaN    7.000000
          M           NaN     NaN    NaN    NaN      NaN    77.0         NaN
Delhi     F          86.0    54.0   53.0   76.0     59.0     NaN  131.000000
          M         107.0    16.0  109.0    NaN     40.0     NaN         NaN
Gurgaon   F          72.0     NaN    NaN   85.0      NaN    34.0   84.000000
          M         113.0     NaN    NaN    NaN      NaN     NaN         NaN
Hyderabad F           NaN     NaN    NaN    NaN      NaN     NaN         NaN
          M           NaN     NaN   72.0   74.0      NaN     NaN  142.000000
Jaipur    F           NaN   146.0  102.0  107.0      NaN     NaN         NaN
          M           NaN    85.0    NaN    NaN      9.0   108.0         NaN
Kolkata   F          73.0     NaN    NaN  116.0      NaN    50.0         NaN
          M           NaN     NaN    NaN    NaN    133.0     NaN         NaN
Mumbai    F           NaN     NaN    NaN    NaN    144.0     NaN         NaN
          M           NaN     NaN    NaN   84.0      NaN     NaN         NaN
Patna     F           NaN     NaN   14.0    NaN     68.0    98.0  114.000000
          M          76.0     NaN   11.0    NaN      NaN     NaN         NaN
Pune      F          81.0     NaN   20.0    NaN     59.0     NaN   38.000000
          M           NaN     NaN    NaN  141.0      NaN   116.0         NaN

Item              Pizza      Samosa    Sandwich  Thali   Vada
City      Gender
Bengaluru F         NaN         NaN   76.000000   80.0    NaN
          M        19.0   69.333333   89.000000    NaN    NaN
Chennai   F         NaN  142.000000         NaN    NaN  126.0
          M         NaN   94.500000         NaN  114.0  124.5
Delhi     F         NaN         NaN         NaN   23.0    NaN
          M         NaN  102.000000   59.500000    NaN    NaN
Gurgaon   F        15.0   84.000000  102.000000    NaN    NaN
          M        78.0   63.000000  113.000000   43.0  109.0
Hyderabad F         NaN         NaN         NaN  144.0    6.0
          M        70.0         NaN   68.000000    NaN  137.0
Jaipur    F         NaN         NaN         NaN  103.0    NaN
          M        61.0   65.000000  129.000000    NaN    NaN
Kolkata   F        36.0         NaN         NaN    NaN    NaN
          M        63.0         NaN   52.000000    NaN   45.0
Mumbai    F        88.0   80.000000  113.000000  147.0    NaN
          M       131.5         NaN         NaN    NaN  112.0
Patna     F         NaN  140.000000   67.000000    NaN    NaN
          M       103.0         NaN         NaN    NaN    NaN
Pune      F         NaN   30.000000         NaN  134.0   99.0
          M         NaN  122.000000   79.666667    NaN    NaN

In [13]:
df.pivot_table(index=['City', 'Gender'], columns=['Item', 'Frequency'], values='Spends', aggfunc='mean')

Item             Biryani                Burger                 Dosa        \
Frequency          Daily Monthly   Once  Daily  Never Weekly  Daily Never
City      Gender
Bengaluru F          NaN     NaN    NaN  122.0    NaN    NaN    NaN   NaN
          M          NaN     NaN    NaN    NaN    NaN    NaN    NaN  44.0
Chennai   F          NaN     NaN    NaN    NaN    NaN    NaN    NaN   NaN
          M          NaN     NaN    NaN    NaN    NaN    NaN    NaN   NaN
Delhi     F          NaN    86.0    NaN    NaN    NaN   54.0    NaN   NaN
          M        107.0     NaN    NaN    NaN    NaN   16.0  109.0   NaN
Gurgaon   F          NaN    72.0    NaN    NaN    NaN    NaN    NaN   NaN
          M          NaN     NaN  113.0    NaN    NaN    NaN    NaN   NaN
Hyderabad F          NaN     NaN    NaN    NaN    NaN    NaN    NaN   NaN
          M          NaN     NaN    NaN    NaN    NaN    NaN   72.0   NaN
Jaipur    F          NaN     NaN    NaN    NaN  146.0    NaN  102.0   NaN
          M          NaN     NaN    NaN    NaN   85.0    NaN    NaN   NaN
Kolkata   F         38.0     NaN  108.0    NaN    NaN    NaN    NaN   NaN
          M          NaN     NaN    NaN    NaN    NaN    NaN    NaN   NaN
Mumbai    F          NaN     NaN    NaN    NaN    NaN    NaN    NaN   NaN
          M          NaN     NaN    NaN    NaN    NaN    NaN    NaN   NaN
Patna     F          NaN     NaN    NaN    NaN    NaN    NaN   14.0   NaN
          M          NaN     NaN   76.0    NaN    NaN    NaN    NaN   NaN
Pune      F         81.0     NaN    NaN    NaN    NaN    NaN    NaN   NaN
          M          NaN     NaN    NaN    NaN    NaN    NaN    NaN   NaN

Item                           ... Thali                               Vada  \
Frequency         Once Weekly  ... Daily Monthly  Never   Once Weekly Daily
City      Gender               ...
Bengaluru F        NaN    NaN  ...   NaN     NaN    NaN   80.0    NaN   NaN
          M        NaN    NaN  ...   NaN     NaN    NaN    NaN    NaN   NaN
Chennai   F       20.0    NaN  ...   NaN     NaN    NaN    NaN    NaN   NaN
          M        NaN    NaN  ...   NaN     NaN    NaN    NaN  114.0   NaN
Delhi     F       53.0    NaN  ...   NaN    23.0    NaN    NaN    NaN   NaN
          M        NaN    NaN  ...   NaN     NaN    NaN    NaN    NaN   NaN
Gurgaon   F        NaN    NaN  ...   NaN     NaN    NaN    NaN    NaN   NaN
          M        NaN    NaN  ...  43.0     NaN    NaN    NaN    NaN   NaN
Hyderabad F        NaN    NaN  ...   NaN     NaN  144.0    NaN    NaN   NaN
          M        NaN    NaN  ...   NaN     NaN    NaN    NaN    NaN   NaN
Jaipur    F        NaN    NaN  ...   NaN     NaN    NaN    NaN  103.0   NaN
          M        NaN    NaN  ...   NaN     NaN    NaN    NaN    NaN   NaN
Kolkata   F        NaN    NaN  ...   NaN     NaN    NaN    NaN    NaN   NaN
          M        NaN    NaN  ...   NaN     NaN    NaN    NaN    NaN  45.0
Mumbai    F        NaN    NaN  ...   NaN     NaN    NaN  147.0    NaN   NaN
          M        NaN    NaN  ...   NaN     NaN    NaN    NaN    NaN   NaN
Patna     F        NaN    NaN  ...   NaN     NaN    NaN    NaN    NaN   NaN
          M        NaN   11.0  ...   NaN     NaN    NaN    NaN    NaN   NaN
Pune      F        NaN   20.0  ...   NaN     NaN  134.0    NaN    NaN   NaN
          M        NaN    NaN  ...   NaN     NaN    NaN    NaN    NaN   NaN

Item
Frequency        Monthly  Never   Once Weekly
City      Gender
Bengaluru F          NaN    NaN    NaN    NaN
          M          NaN    NaN    NaN    NaN
Chennai   F          NaN    NaN  126.0    NaN
          M          NaN    NaN    NaN  124.5
Delhi     F          NaN    NaN    NaN    NaN
          M          NaN    NaN    NaN    NaN
Gurgaon   F          NaN    NaN    NaN    NaN
          M          NaN    NaN    NaN  109.0
Hyderabad F          NaN    NaN    NaN    6.0
          M          NaN    NaN    NaN  137.0
Jaipur    F          NaN    NaN    NaN    NaN
          M          NaN    NaN    NaN    NaN
Kolkata   F          NaN    NaN    NaN    NaN
          M          NaN    NaN    NaN    NaN
Mumbai    F          NaN    NaN    NaN    NaN
          M          NaN  134.0  101.0    NaN
Patna     F          NaN    NaN    NaN    NaN
          M          NaN    NaN    NaN    NaN
Pune      F         99.0    NaN    NaN    NaN
          M          NaN    NaN    NaN    NaN

[20 rows x 49 columns]