### Write an operation to show the orange cap holder of each season in IPL

In [2]:
import pandas as pd

In [3]:
matches = pd.read_csv('../matches.csv')
deliveries = pd.read_csv('../deliveries.csv')

#### Merging the matches and deliveries DataFrame to get the orange cap holders

In [5]:
new_df = deliveries.merge(matches, left_on='match_id', right_on='id')
print(deliveries.shape)
print(matches.shape)
print(new_df.shape)

(150460, 21)
(636, 18)
(150460, 39)

In [11]:
all_batsman = new_df.groupby(['season', 'batsman'])['batsman_runs'].sum().sort_values(ascending=False)

In [21]:
sorted_df = all_batsman.reset_index().drop_duplicates('season', keep='first').sort_values('season')
sorted_df

    season       batsman  batsman_runs
10    2008      SE Marsh           616
14    2009     ML Hayden           572
9     2010  SR Tendulkar           618
11    2011      CH Gayle           608
3     2012      CH Gayle           733
2     2013    MEK Hussey           733
6     2014    RV Uthappa           660
17    2015     DA Warner           562
0     2016       V Kohli           973
7     2017     DA Warner           641

### Showing season and its batsman

In [22]:
sorted_df[['season', 'batsman']]

    season       batsman
10    2008      SE Marsh
14    2009     ML Hayden
9     2010  SR Tendulkar
11    2011      CH Gayle
3     2012      CH Gayle
2     2013    MEK Hussey
6     2014    RV Uthappa
17    2015     DA Warner
0     2016       V Kohli
7     2017     DA Warner